# Generated by Django 2.2.10 on 2020-05-23 02:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.CharField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_string_tension', models.PositiveSmallIntegerField(default=56, validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(20)])),
                ('cross_string_tension', models.PositiveSmallIntegerField(default=56, validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(20)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('is_complete', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Racket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('recommended_tension_lbs', models.CharField(max_length=20)),
                ('string_length', models.CharField(max_length=20)),
                ('string_pattern', models.CharField(max_length=20)),
                ('main_holes_skipped', models.CharField(max_length=40)),
                ('main_holes_tied', models.CharField(max_length=10)),
                ('cross_holes_started', models.CharField(max_length=10)),
                ('cross_holes_tied', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='String',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddConstraint(
            model_name='string',
            constraint=models.UniqueConstraint(fields=('brand', 'name'), name='unique_string_name'),
        ),
        migrations.AddConstraint(
            model_name='racket',
            constraint=models.UniqueConstraint(fields=('brand', 'model'), name='unique_racket_name'),
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='cross_string',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='racket_stringer.String'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racket_stringer.Customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='main_string',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='racket_stringer.String'),
        ),
        migrations.AddField(
            model_name='order',
            name='racket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racket_stringer.Racket'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='unique_customer_name'),
        ),
    ]
