# Generated by Django 5.0 on 2025-05-16 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racket_stringer', '0003_auto_20220529_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-due_date']},
        ),
    ]
