# Generated by Django 5.1.9 on 2025-05-16 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racket_stringer', '0004_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='racket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racket_stringer.racket'),
        ),
    ]
